server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: dPTdwrAE28umMn0kuEpmi90I6WP4nXJDv/XQFvq+0v62zloA80nHfPwN5n1ejDdUqS762XGfdgOo7ig7InaocQ==
